name: Actions Tests
on:
  pull_request:
    types: [ labeled ]
jobs:
  print_hello_world:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello World
      run: echo "Hello World"
      if: ${{ github.event.label.name == 'bug' }}
